// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Popover as _Popover } from '@base-ui/react';
import type {
  PopoverRootProps,
  PopoverTriggerProps,
  PopoverPortalProps,
  PopoverPositionerProps,
  PopoverPopupProps,
  PopoverArrowProps,
  PopoverBackdropProps,
  PopoverTitleProps,
  PopoverDescriptionProps,
  PopoverCloseProps,
  PopoverViewportProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: PopoverRootProps) {
  return <_Popover.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: PopoverTriggerProps) {
  return <_Popover.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: PopoverPortalProps) {
  return <_Popover.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Positioner({ className, ...props }: PopoverPositionerProps) {
  return <_Popover.Positioner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: PopoverPopupProps) {
  return <_Popover.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Arrow({ className, ...props }: PopoverArrowProps) {
  return <_Popover.Arrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Backdrop({ className, ...props }: PopoverBackdropProps) {
  return <_Popover.Backdrop className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Title({ className, ...props }: PopoverTitleProps) {
  return <_Popover.Title className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Description({ className, ...props }: PopoverDescriptionProps) {
  return <_Popover.Description className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Close({ className, ...props }: PopoverCloseProps) {
  return <_Popover.Close className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: PopoverViewportProps) {
  return <_Popover.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Popover = { Root, Trigger, Portal, Positioner, Popup, Arrow, Backdrop, Title, Description, Close, Viewport };

export type {
  PopoverRootProps,
  PopoverTriggerProps,
  PopoverPortalProps,
  PopoverPositionerProps,
  PopoverPopupProps,
  PopoverArrowProps,
  PopoverBackdropProps,
  PopoverTitleProps,
  PopoverDescriptionProps,
  PopoverCloseProps,
  PopoverViewportProps,
} from '@base-ui/react';
