// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { PreviewCard as _PreviewCard } from '@base-ui/react';
import type {
  PreviewCardRootProps,
  PreviewCardPortalProps,
  PreviewCardTriggerProps,
  PreviewCardPositionerProps,
  PreviewCardPopupProps,
  PreviewCardArrowProps,
  PreviewCardBackdropProps,
  PreviewCardViewportProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: PreviewCardRootProps) {
  return <_PreviewCard.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: PreviewCardPortalProps) {
  return <_PreviewCard.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: PreviewCardTriggerProps) {
  return <_PreviewCard.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Positioner({ className, ...props }: PreviewCardPositionerProps) {
  return <_PreviewCard.Positioner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: PreviewCardPopupProps) {
  return <_PreviewCard.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Arrow({ className, ...props }: PreviewCardArrowProps) {
  return <_PreviewCard.Arrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Backdrop({ className, ...props }: PreviewCardBackdropProps) {
  return <_PreviewCard.Backdrop className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: PreviewCardViewportProps) {
  return <_PreviewCard.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const PreviewCard = { Root, Portal, Trigger, Positioner, Popup, Arrow, Backdrop, Viewport };

export type {
  PreviewCardRootProps,
  PreviewCardPortalProps,
  PreviewCardTriggerProps,
  PreviewCardPositionerProps,
  PreviewCardPopupProps,
  PreviewCardArrowProps,
  PreviewCardBackdropProps,
  PreviewCardViewportProps,
} from '@base-ui/react';
