// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { ToggleGroup as _ToggleGroup } from '@base-ui/react';
import type { ToggleGroupProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function ToggleGroup({ className, ...props }: ToggleGroupProps) {
  return <_ToggleGroup className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/toggle-group';
