// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Autocomplete as _Autocomplete } from '@base-ui/react';
import type {
  AutocompleteRootProps,
  AutocompleteValueProps,
  AutocompleteTriggerProps,
  AutocompleteInputGroupProps,
  AutocompleteItemProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: AutocompleteRootProps) {
  return <_Autocomplete.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Value({ className, ...props }: AutocompleteValueProps) {
  return <_Autocomplete.Value className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: AutocompleteTriggerProps) {
  return <_Autocomplete.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function InputGroup({ className, ...props }: AutocompleteInputGroupProps) {
  return <_Autocomplete.InputGroup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Item({ className, ...props }: AutocompleteItemProps) {
  return <_Autocomplete.Item className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Autocomplete = { Root, Value, Trigger, InputGroup, Item };

export type {
  AutocompleteRootProps,
  AutocompleteValueProps,
  AutocompleteTriggerProps,
  AutocompleteInputGroupProps,
  AutocompleteItemProps,
} from '@base-ui/react';
