// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { CSPProvider as _CSPProvider } from '@base-ui/react';
import type { CSPProviderProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function CSPProvider({ className, ...props }: CSPProviderProps) {
  return <_CSPProvider className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/csp-provider';
