// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Radio as _Radio } from '@base-ui/react';
import type {
  RadioRootProps,
  RadioIndicatorProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: RadioRootProps) {
  return <_Radio.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Indicator({ className, ...props }: RadioIndicatorProps) {
  return <_Radio.Indicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Radio = { Root, Indicator };

export type {
  RadioRootProps,
  RadioIndicatorProps,
} from '@base-ui/react';
