// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Input as _Input } from '@base-ui/react';
import type { InputProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function Input({ className, ...props }: InputProps) {
  return <_Input className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/input';
