// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Separator as _Separator } from '@base-ui/react';
import type { SeparatorProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function Separator({ className, ...props }: SeparatorProps) {
  return <_Separator className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/separator';
