// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { ScrollArea as _ScrollArea } from '@base-ui/react';
import type {
  ScrollAreaRootProps,
  ScrollAreaViewportProps,
  ScrollAreaScrollbarProps,
  ScrollAreaContentProps,
  ScrollAreaThumbProps,
  ScrollAreaCornerProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: ScrollAreaRootProps) {
  return <_ScrollArea.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: ScrollAreaViewportProps) {
  return <_ScrollArea.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Scrollbar({ className, ...props }: ScrollAreaScrollbarProps) {
  return <_ScrollArea.Scrollbar className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Content({ className, ...props }: ScrollAreaContentProps) {
  return <_ScrollArea.Content className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Thumb({ className, ...props }: ScrollAreaThumbProps) {
  return <_ScrollArea.Thumb className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Corner({ className, ...props }: ScrollAreaCornerProps) {
  return <_ScrollArea.Corner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const ScrollArea = { Root, Viewport, Scrollbar, Content, Thumb, Corner };

export type {
  ScrollAreaRootProps,
  ScrollAreaViewportProps,
  ScrollAreaScrollbarProps,
  ScrollAreaContentProps,
  ScrollAreaThumbProps,
  ScrollAreaCornerProps,
} from '@base-ui/react';
