// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { OTPField as _OTPField } from '@base-ui/react';
import type {
  OTPFieldRootProps,
  OTPFieldInputProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: OTPFieldRootProps) {
  return <_OTPField.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Input({ className, ...props }: OTPFieldInputProps) {
  return <_OTPField.Input className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const OTPField = { Root, Input };

export type {
  OTPFieldRootProps,
  OTPFieldInputProps,
} from '@base-ui/react';
