// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { NavigationMenu as _NavigationMenu } from '@base-ui/react';
import type {
  NavigationMenuRootProps,
  NavigationMenuListProps,
  NavigationMenuItemProps,
  NavigationMenuContentProps,
  NavigationMenuTriggerProps,
  NavigationMenuPortalProps,
  NavigationMenuPositionerProps,
  NavigationMenuViewportProps,
  NavigationMenuBackdropProps,
  NavigationMenuPopupProps,
  NavigationMenuArrowProps,
  NavigationMenuLinkProps,
  NavigationMenuIconProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: NavigationMenuRootProps) {
  return <_NavigationMenu.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function List({ className, ...props }: NavigationMenuListProps) {
  return <_NavigationMenu.List className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Item({ className, ...props }: NavigationMenuItemProps) {
  return <_NavigationMenu.Item className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Content({ className, ...props }: NavigationMenuContentProps) {
  return <_NavigationMenu.Content className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: NavigationMenuTriggerProps) {
  return <_NavigationMenu.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: NavigationMenuPortalProps) {
  return <_NavigationMenu.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Positioner({ className, ...props }: NavigationMenuPositionerProps) {
  return <_NavigationMenu.Positioner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: NavigationMenuViewportProps) {
  return <_NavigationMenu.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Backdrop({ className, ...props }: NavigationMenuBackdropProps) {
  return <_NavigationMenu.Backdrop className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: NavigationMenuPopupProps) {
  return <_NavigationMenu.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Arrow({ className, ...props }: NavigationMenuArrowProps) {
  return <_NavigationMenu.Arrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Link({ className, ...props }: NavigationMenuLinkProps) {
  return <_NavigationMenu.Link className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Icon({ className, ...props }: NavigationMenuIconProps) {
  return <_NavigationMenu.Icon className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const NavigationMenu = { Root, List, Item, Content, Trigger, Portal, Positioner, Viewport, Backdrop, Popup, Arrow, Link, Icon };

export type {
  NavigationMenuRootProps,
  NavigationMenuListProps,
  NavigationMenuItemProps,
  NavigationMenuContentProps,
  NavigationMenuTriggerProps,
  NavigationMenuPortalProps,
  NavigationMenuPositionerProps,
  NavigationMenuViewportProps,
  NavigationMenuBackdropProps,
  NavigationMenuPopupProps,
  NavigationMenuArrowProps,
  NavigationMenuLinkProps,
  NavigationMenuIconProps,
} from '@base-ui/react';
