// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

export { NavigationMenu } from '@base-ui/react';
export type * from '@base-ui/react/navigation-menu';
