// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Combobox as _Combobox } from '@base-ui/react';
import type {
  ComboboxRootProps,
  ComboboxLabelProps,
  ComboboxValueProps,
  ComboboxInputProps,
  ComboboxInputGroupProps,
  ComboboxTriggerProps,
  ComboboxListProps,
  ComboboxStatusProps,
  ComboboxPortalProps,
  ComboboxBackdropProps,
  ComboboxPositionerProps,
  ComboboxPopupProps,
  ComboboxArrowProps,
  ComboboxIconProps,
  ComboboxGroupProps,
  ComboboxGroupLabelProps,
  ComboboxItemProps,
  ComboboxItemIndicatorProps,
  ComboboxChipsProps,
  ComboboxChipProps,
  ComboboxChipRemoveProps,
  ComboboxRowProps,
  ComboboxCollectionProps,
  ComboboxEmptyProps,
  ComboboxClearProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: ComboboxRootProps) {
  return <_Combobox.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Label({ className, ...props }: ComboboxLabelProps) {
  return <_Combobox.Label className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Value({ className, ...props }: ComboboxValueProps) {
  return <_Combobox.Value className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Input({ className, ...props }: ComboboxInputProps) {
  return <_Combobox.Input className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function InputGroup({ className, ...props }: ComboboxInputGroupProps) {
  return <_Combobox.InputGroup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: ComboboxTriggerProps) {
  return <_Combobox.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function List({ className, ...props }: ComboboxListProps) {
  return <_Combobox.List className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Status({ className, ...props }: ComboboxStatusProps) {
  return <_Combobox.Status className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: ComboboxPortalProps) {
  return <_Combobox.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Backdrop({ className, ...props }: ComboboxBackdropProps) {
  return <_Combobox.Backdrop className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Positioner({ className, ...props }: ComboboxPositionerProps) {
  return <_Combobox.Positioner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: ComboboxPopupProps) {
  return <_Combobox.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Arrow({ className, ...props }: ComboboxArrowProps) {
  return <_Combobox.Arrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Icon({ className, ...props }: ComboboxIconProps) {
  return <_Combobox.Icon className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Group({ className, ...props }: ComboboxGroupProps) {
  return <_Combobox.Group className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function GroupLabel({ className, ...props }: ComboboxGroupLabelProps) {
  return <_Combobox.GroupLabel className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Item({ className, ...props }: ComboboxItemProps) {
  return <_Combobox.Item className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function ItemIndicator({ className, ...props }: ComboboxItemIndicatorProps) {
  return <_Combobox.ItemIndicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Chips({ className, ...props }: ComboboxChipsProps) {
  return <_Combobox.Chips className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Chip({ className, ...props }: ComboboxChipProps) {
  return <_Combobox.Chip className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function ChipRemove({ className, ...props }: ComboboxChipRemoveProps) {
  return <_Combobox.ChipRemove className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Row({ className, ...props }: ComboboxRowProps) {
  return <_Combobox.Row className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Collection({ className, ...props }: ComboboxCollectionProps) {
  return <_Combobox.Collection className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Empty({ className, ...props }: ComboboxEmptyProps) {
  return <_Combobox.Empty className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Clear({ className, ...props }: ComboboxClearProps) {
  return <_Combobox.Clear className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Combobox = { Root, Label, Value, Input, InputGroup, Trigger, List, Status, Portal, Backdrop, Positioner, Popup, Arrow, Icon, Group, GroupLabel, Item, ItemIndicator, Chips, Chip, ChipRemove, Row, Collection, Empty, Clear, useFilter: _Combobox.useFilter, useFilteredItems: _Combobox.useFilteredItems };

export type {
  ComboboxRootProps,
  ComboboxLabelProps,
  ComboboxValueProps,
  ComboboxInputProps,
  ComboboxInputGroupProps,
  ComboboxTriggerProps,
  ComboboxListProps,
  ComboboxStatusProps,
  ComboboxPortalProps,
  ComboboxBackdropProps,
  ComboboxPositionerProps,
  ComboboxPopupProps,
  ComboboxArrowProps,
  ComboboxIconProps,
  ComboboxGroupProps,
  ComboboxGroupLabelProps,
  ComboboxItemProps,
  ComboboxItemIndicatorProps,
  ComboboxChipsProps,
  ComboboxChipProps,
  ComboboxChipRemoveProps,
  ComboboxRowProps,
  ComboboxCollectionProps,
  ComboboxEmptyProps,
  ComboboxClearProps,
} from '@base-ui/react';
