// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Button as _Button } from '@base-ui/react';
import type { ButtonProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function Button({ className, ...props }: ButtonProps) {
  return <_Button className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/button';
