// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Menu as _Menu } from '@base-ui/react';
import type {
  MenuArrowProps,
  MenuBackdropProps,
  MenuCheckboxItemProps,
  MenuCheckboxItemIndicatorProps,
  MenuGroupProps,
  MenuGroupLabelProps,
  MenuItemProps,
  MenuLinkItemProps,
  MenuPopupProps,
  MenuPortalProps,
  MenuPositionerProps,
  MenuRadioGroupProps,
  MenuRadioItemProps,
  MenuRadioItemIndicatorProps,
  MenuRootProps,
  MenuSubmenuRootProps,
  MenuTriggerProps,
  MenuViewportProps,
  MenuSubmenuTriggerProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Arrow({ className, ...props }: MenuArrowProps) {
  return <_Menu.Arrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Backdrop({ className, ...props }: MenuBackdropProps) {
  return <_Menu.Backdrop className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function CheckboxItem({ className, ...props }: MenuCheckboxItemProps) {
  return <_Menu.CheckboxItem className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function CheckboxItemIndicator({ className, ...props }: MenuCheckboxItemIndicatorProps) {
  return <_Menu.CheckboxItemIndicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Group({ className, ...props }: MenuGroupProps) {
  return <_Menu.Group className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function GroupLabel({ className, ...props }: MenuGroupLabelProps) {
  return <_Menu.GroupLabel className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Item({ className, ...props }: MenuItemProps) {
  return <_Menu.Item className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function LinkItem({ className, ...props }: MenuLinkItemProps) {
  return <_Menu.LinkItem className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: MenuPopupProps) {
  return <_Menu.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: MenuPortalProps) {
  return <_Menu.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Positioner({ className, ...props }: MenuPositionerProps) {
  return <_Menu.Positioner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function RadioGroup({ className, ...props }: MenuRadioGroupProps) {
  return <_Menu.RadioGroup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function RadioItem({ className, ...props }: MenuRadioItemProps) {
  return <_Menu.RadioItem className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function RadioItemIndicator({ className, ...props }: MenuRadioItemIndicatorProps) {
  return <_Menu.RadioItemIndicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Root({ className, ...props }: MenuRootProps) {
  return <_Menu.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function SubmenuRoot({ className, ...props }: MenuSubmenuRootProps) {
  return <_Menu.SubmenuRoot className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: MenuTriggerProps) {
  return <_Menu.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: MenuViewportProps) {
  return <_Menu.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function SubmenuTrigger({ className, ...props }: MenuSubmenuTriggerProps) {
  return <_Menu.SubmenuTrigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Menu = { Arrow, Backdrop, CheckboxItem, CheckboxItemIndicator, Group, GroupLabel, Item, LinkItem, Popup, Portal, Positioner, RadioGroup, RadioItem, RadioItemIndicator, Root, SubmenuRoot, Trigger, Viewport, SubmenuTrigger };

export type {
  MenuArrowProps,
  MenuBackdropProps,
  MenuCheckboxItemProps,
  MenuCheckboxItemIndicatorProps,
  MenuGroupProps,
  MenuGroupLabelProps,
  MenuItemProps,
  MenuLinkItemProps,
  MenuPopupProps,
  MenuPortalProps,
  MenuPositionerProps,
  MenuRadioGroupProps,
  MenuRadioItemProps,
  MenuRadioItemIndicatorProps,
  MenuRootProps,
  MenuSubmenuRootProps,
  MenuTriggerProps,
  MenuViewportProps,
  MenuSubmenuTriggerProps,
} from '@base-ui/react';
