// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Form as _Form } from '@base-ui/react';
import type { FormProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function Form({ className, ...props }: FormProps) {
  return <_Form className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/form';
