// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { DirectionProvider as _DirectionProvider } from '@base-ui/react';
import type { DirectionProviderProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function DirectionProvider({ className, ...props }: DirectionProviderProps) {
  return <_DirectionProvider className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export { useDirection } from '@base-ui/react';

export type * from '@base-ui/react/direction-provider';
