// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { RadioGroup as _RadioGroup } from '@base-ui/react';
import type { RadioGroupProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function RadioGroup({ className, ...props }: RadioGroupProps) {
  return <_RadioGroup className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/radio-group';
