// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Tabs as _Tabs } from '@base-ui/react';
import type {
  TabsRootProps,
  TabsTabProps,
  TabsIndicatorProps,
  TabsPanelProps,
  TabsListProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: TabsRootProps) {
  return <_Tabs.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Tab({ className, ...props }: TabsTabProps) {
  return <_Tabs.Tab className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Indicator({ className, ...props }: TabsIndicatorProps) {
  return <_Tabs.Indicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Panel({ className, ...props }: TabsPanelProps) {
  return <_Tabs.Panel className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function List({ className, ...props }: TabsListProps) {
  return <_Tabs.List className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Tabs = { Root, Tab, Indicator, Panel, List };

export type {
  TabsRootProps,
  TabsTabProps,
  TabsIndicatorProps,
  TabsPanelProps,
  TabsListProps,
} from '@base-ui/react';
