// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Toast as _Toast } from '@base-ui/react';
import type {
  ToastProviderProps,
  ToastViewportProps,
  ToastRootProps,
  ToastContentProps,
  ToastDescriptionProps,
  ToastTitleProps,
  ToastCloseProps,
  ToastActionProps,
  ToastPortalProps,
  ToastPositionerProps,
  ToastArrowProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Provider({ className, ...props }: ToastProviderProps) {
  return <_Toast.Provider className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: ToastViewportProps) {
  return <_Toast.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Root({ className, ...props }: ToastRootProps) {
  return <_Toast.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Content({ className, ...props }: ToastContentProps) {
  return <_Toast.Content className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Description({ className, ...props }: ToastDescriptionProps) {
  return <_Toast.Description className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Title({ className, ...props }: ToastTitleProps) {
  return <_Toast.Title className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Close({ className, ...props }: ToastCloseProps) {
  return <_Toast.Close className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Action({ className, ...props }: ToastActionProps) {
  return <_Toast.Action className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: ToastPortalProps) {
  return <_Toast.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Positioner({ className, ...props }: ToastPositionerProps) {
  return <_Toast.Positioner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Arrow({ className, ...props }: ToastArrowProps) {
  return <_Toast.Arrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Toast = { Provider, Viewport, Root, Content, Description, Title, Close, Action, Portal, Positioner, Arrow, useToastManager: _Toast.useToastManager, createToastManager: _Toast.createToastManager };

export type {
  ToastProviderProps,
  ToastViewportProps,
  ToastRootProps,
  ToastContentProps,
  ToastDescriptionProps,
  ToastTitleProps,
  ToastCloseProps,
  ToastActionProps,
  ToastPortalProps,
  ToastPositionerProps,
  ToastArrowProps,
} from '@base-ui/react';
