// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Switch as _Switch } from '@base-ui/react';
import type {
  SwitchRootProps,
  SwitchThumbProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: SwitchRootProps) {
  return <_Switch.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Thumb({ className, ...props }: SwitchThumbProps) {
  return <_Switch.Thumb className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Switch = { Root, Thumb };

export type {
  SwitchRootProps,
  SwitchThumbProps,
} from '@base-ui/react';
