// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

export { Switch } from '@base-ui/react';
export type * from '@base-ui/react/switch';
