// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { NumberField as _NumberField } from '@base-ui/react';
import type {
  NumberFieldRootProps,
  NumberFieldGroupProps,
  NumberFieldIncrementProps,
  NumberFieldDecrementProps,
  NumberFieldInputProps,
  NumberFieldScrubAreaProps,
  NumberFieldScrubAreaCursorProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: NumberFieldRootProps) {
  return <_NumberField.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Group({ className, ...props }: NumberFieldGroupProps) {
  return <_NumberField.Group className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Increment({ className, ...props }: NumberFieldIncrementProps) {
  return <_NumberField.Increment className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Decrement({ className, ...props }: NumberFieldDecrementProps) {
  return <_NumberField.Decrement className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Input({ className, ...props }: NumberFieldInputProps) {
  return <_NumberField.Input className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function ScrubArea({ className, ...props }: NumberFieldScrubAreaProps) {
  return <_NumberField.ScrubArea className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function ScrubAreaCursor({ className, ...props }: NumberFieldScrubAreaCursorProps) {
  return <_NumberField.ScrubAreaCursor className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const NumberField = { Root, Group, Increment, Decrement, Input, ScrubArea, ScrubAreaCursor };

export type {
  NumberFieldRootProps,
  NumberFieldGroupProps,
  NumberFieldIncrementProps,
  NumberFieldDecrementProps,
  NumberFieldInputProps,
  NumberFieldScrubAreaProps,
  NumberFieldScrubAreaCursorProps,
} from '@base-ui/react';
