// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Toolbar as _Toolbar } from '@base-ui/react';
import type {
  ToolbarSeparatorProps,
  ToolbarRootProps,
  ToolbarGroupProps,
  ToolbarButtonProps,
  ToolbarLinkProps,
  ToolbarInputProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Separator({ className, ...props }: ToolbarSeparatorProps) {
  return <_Toolbar.Separator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Root({ className, ...props }: ToolbarRootProps) {
  return <_Toolbar.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Group({ className, ...props }: ToolbarGroupProps) {
  return <_Toolbar.Group className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Button({ className, ...props }: ToolbarButtonProps) {
  return <_Toolbar.Button className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Link({ className, ...props }: ToolbarLinkProps) {
  return <_Toolbar.Link className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Input({ className, ...props }: ToolbarInputProps) {
  return <_Toolbar.Input className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Toolbar = { Separator, Root, Group, Button, Link, Input };

export type {
  ToolbarSeparatorProps,
  ToolbarRootProps,
  ToolbarGroupProps,
  ToolbarButtonProps,
  ToolbarLinkProps,
  ToolbarInputProps,
} from '@base-ui/react';
