// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Progress as _Progress } from '@base-ui/react';
import type {
  ProgressRootProps,
  ProgressTrackProps,
  ProgressIndicatorProps,
  ProgressValueProps,
  ProgressLabelProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: ProgressRootProps) {
  return <_Progress.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Track({ className, ...props }: ProgressTrackProps) {
  return <_Progress.Track className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Indicator({ className, ...props }: ProgressIndicatorProps) {
  return <_Progress.Indicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Value({ className, ...props }: ProgressValueProps) {
  return <_Progress.Value className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Label({ className, ...props }: ProgressLabelProps) {
  return <_Progress.Label className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Progress = { Root, Track, Indicator, Value, Label };

export type {
  ProgressRootProps,
  ProgressTrackProps,
  ProgressIndicatorProps,
  ProgressValueProps,
  ProgressLabelProps,
} from '@base-ui/react';
