// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

export { Progress } from '@base-ui/react';
export type * from '@base-ui/react/progress';
