// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Fieldset as _Fieldset } from '@base-ui/react';
import type {
  FieldsetRootProps,
  FieldsetLegendProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: FieldsetRootProps) {
  return <_Fieldset.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Legend({ className, ...props }: FieldsetLegendProps) {
  return <_Fieldset.Legend className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Fieldset = { Root, Legend };

export type {
  FieldsetRootProps,
  FieldsetLegendProps,
} from '@base-ui/react';
