// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Select as _Select } from '@base-ui/react';
import type {
  SelectRootProps,
  SelectLabelProps,
  SelectTriggerProps,
  SelectValueProps,
  SelectIconProps,
  SelectPortalProps,
  SelectBackdropProps,
  SelectPositionerProps,
  SelectPopupProps,
  SelectListProps,
  SelectItemProps,
  SelectItemIndicatorProps,
  SelectItemTextProps,
  SelectArrowProps,
  SelectScrollDownArrowProps,
  SelectScrollUpArrowProps,
  SelectGroupProps,
  SelectGroupLabelProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: SelectRootProps) {
  return <_Select.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Label({ className, ...props }: SelectLabelProps) {
  return <_Select.Label className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: SelectTriggerProps) {
  return <_Select.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Value({ className, ...props }: SelectValueProps) {
  return <_Select.Value className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Icon({ className, ...props }: SelectIconProps) {
  return <_Select.Icon className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: SelectPortalProps) {
  return <_Select.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Backdrop({ className, ...props }: SelectBackdropProps) {
  return <_Select.Backdrop className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Positioner({ className, ...props }: SelectPositionerProps) {
  return <_Select.Positioner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: SelectPopupProps) {
  return <_Select.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function List({ className, ...props }: SelectListProps) {
  return <_Select.List className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Item({ className, ...props }: SelectItemProps) {
  return <_Select.Item className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function ItemIndicator({ className, ...props }: SelectItemIndicatorProps) {
  return <_Select.ItemIndicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function ItemText({ className, ...props }: SelectItemTextProps) {
  return <_Select.ItemText className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Arrow({ className, ...props }: SelectArrowProps) {
  return <_Select.Arrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function ScrollDownArrow({ className, ...props }: SelectScrollDownArrowProps) {
  return <_Select.ScrollDownArrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function ScrollUpArrow({ className, ...props }: SelectScrollUpArrowProps) {
  return <_Select.ScrollUpArrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Group({ className, ...props }: SelectGroupProps) {
  return <_Select.Group className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function GroupLabel({ className, ...props }: SelectGroupLabelProps) {
  return <_Select.GroupLabel className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Select = { Root, Label, Trigger, Value, Icon, Portal, Backdrop, Positioner, Popup, List, Item, ItemIndicator, ItemText, Arrow, ScrollDownArrow, ScrollUpArrow, Group, GroupLabel };

export type {
  SelectRootProps,
  SelectLabelProps,
  SelectTriggerProps,
  SelectValueProps,
  SelectIconProps,
  SelectPortalProps,
  SelectBackdropProps,
  SelectPositionerProps,
  SelectPopupProps,
  SelectListProps,
  SelectItemProps,
  SelectItemIndicatorProps,
  SelectItemTextProps,
  SelectArrowProps,
  SelectScrollDownArrowProps,
  SelectScrollUpArrowProps,
  SelectGroupProps,
  SelectGroupLabelProps,
} from '@base-ui/react';
