// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { AlertDialog as _AlertDialog } from '@base-ui/react';
import type {
  AlertDialogRootProps,
  AlertDialogTriggerProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: AlertDialogRootProps) {
  return <_AlertDialog.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: AlertDialogTriggerProps) {
  return <_AlertDialog.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const AlertDialog = { Root, Trigger };

export type {
  AlertDialogRootProps,
  AlertDialogTriggerProps,
} from '@base-ui/react';
