// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Field as _Field } from '@base-ui/react';
import type {
  FieldRootProps,
  FieldLabelProps,
  FieldErrorProps,
  FieldDescriptionProps,
  FieldControlProps,
  FieldValidityProps,
  FieldItemProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: FieldRootProps) {
  return <_Field.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Label({ className, ...props }: FieldLabelProps) {
  return <_Field.Label className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Error({ className, ...props }: FieldErrorProps) {
  return <_Field.Error className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Description({ className, ...props }: FieldDescriptionProps) {
  return <_Field.Description className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Control({ className, ...props }: FieldControlProps) {
  return <_Field.Control className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Validity({ className, ...props }: FieldValidityProps) {
  return <_Field.Validity className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Item({ className, ...props }: FieldItemProps) {
  return <_Field.Item className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Field = { Root, Label, Error, Description, Control, Validity, Item };

export type {
  FieldRootProps,
  FieldLabelProps,
  FieldErrorProps,
  FieldDescriptionProps,
  FieldControlProps,
  FieldValidityProps,
  FieldItemProps,
} from '@base-ui/react';
