// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Drawer as _Drawer } from '@base-ui/react';
import type {
  DrawerBackdropProps,
  DrawerCloseProps,
  DrawerContentProps,
  DrawerDescriptionProps,
  DrawerIndentProps,
  DrawerIndentBackgroundProps,
  DrawerPopupProps,
  DrawerPortalProps,
  DrawerProviderProps,
  DrawerRootProps,
  DrawerSwipeAreaProps,
  DrawerTitleProps,
  DrawerTriggerProps,
  DrawerViewportProps,
  DrawerVirtualKeyboardProviderProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Backdrop({ className, ...props }: DrawerBackdropProps) {
  return <_Drawer.Backdrop className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Close({ className, ...props }: DrawerCloseProps) {
  return <_Drawer.Close className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Content({ className, ...props }: DrawerContentProps) {
  return <_Drawer.Content className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Description({ className, ...props }: DrawerDescriptionProps) {
  return <_Drawer.Description className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Indent({ className, ...props }: DrawerIndentProps) {
  return <_Drawer.Indent className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function IndentBackground({ className, ...props }: DrawerIndentBackgroundProps) {
  return <_Drawer.IndentBackground className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: DrawerPopupProps) {
  return <_Drawer.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: DrawerPortalProps) {
  return <_Drawer.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Provider({ className, ...props }: DrawerProviderProps) {
  return <_Drawer.Provider className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Root({ className, ...props }: DrawerRootProps) {
  return <_Drawer.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function SwipeArea({ className, ...props }: DrawerSwipeAreaProps) {
  return <_Drawer.SwipeArea className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Title({ className, ...props }: DrawerTitleProps) {
  return <_Drawer.Title className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: DrawerTriggerProps) {
  return <_Drawer.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: DrawerViewportProps) {
  return <_Drawer.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function VirtualKeyboardProvider({ className, ...props }: DrawerVirtualKeyboardProviderProps) {
  return <_Drawer.VirtualKeyboardProvider className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Drawer = { Backdrop, Close, Content, Description, Indent, IndentBackground, Popup, Portal, Provider, Root, SwipeArea, Title, Trigger, Viewport, VirtualKeyboardProvider };

export type {
  DrawerBackdropProps,
  DrawerCloseProps,
  DrawerContentProps,
  DrawerDescriptionProps,
  DrawerIndentProps,
  DrawerIndentBackgroundProps,
  DrawerPopupProps,
  DrawerPortalProps,
  DrawerProviderProps,
  DrawerRootProps,
  DrawerSwipeAreaProps,
  DrawerTitleProps,
  DrawerTriggerProps,
  DrawerViewportProps,
  DrawerVirtualKeyboardProviderProps,
} from '@base-ui/react';
