// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { ContextMenu as _ContextMenu } from '@base-ui/react';
import type {
  ContextMenuRootProps,
  ContextMenuTriggerProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: ContextMenuRootProps) {
  return <_ContextMenu.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: ContextMenuTriggerProps) {
  return <_ContextMenu.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const ContextMenu = { Root, Trigger };

export type {
  ContextMenuRootProps,
  ContextMenuTriggerProps,
} from '@base-ui/react';
