// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Checkbox as _Checkbox } from '@base-ui/react';
import type {
  CheckboxRootProps,
  CheckboxIndicatorProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: CheckboxRootProps) {
  return <_Checkbox.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Indicator({ className, ...props }: CheckboxIndicatorProps) {
  return <_Checkbox.Indicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Checkbox = { Root, Indicator };

export type {
  CheckboxRootProps,
  CheckboxIndicatorProps,
} from '@base-ui/react';
