// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { CheckboxGroup as _CheckboxGroup } from '@base-ui/react';
import type { CheckboxGroupProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function CheckboxGroup({ className, ...props }: CheckboxGroupProps) {
  return <_CheckboxGroup className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/checkbox-group';
