// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Dialog as _Dialog } from '@base-ui/react';
import type {
  DialogBackdropProps,
  DialogCloseProps,
  DialogDescriptionProps,
  DialogPopupProps,
  DialogPortalProps,
  DialogRootProps,
  DialogViewportProps,
  DialogTitleProps,
  DialogTriggerProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Backdrop({ className, ...props }: DialogBackdropProps) {
  return <_Dialog.Backdrop className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Close({ className, ...props }: DialogCloseProps) {
  return <_Dialog.Close className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Description({ className, ...props }: DialogDescriptionProps) {
  return <_Dialog.Description className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: DialogPopupProps) {
  return <_Dialog.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: DialogPortalProps) {
  return <_Dialog.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Root({ className, ...props }: DialogRootProps) {
  return <_Dialog.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: DialogViewportProps) {
  return <_Dialog.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Title({ className, ...props }: DialogTitleProps) {
  return <_Dialog.Title className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: DialogTriggerProps) {
  return <_Dialog.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Dialog = { Backdrop, Close, Description, Popup, Portal, Root, Viewport, Title, Trigger };

export type {
  DialogBackdropProps,
  DialogCloseProps,
  DialogDescriptionProps,
  DialogPopupProps,
  DialogPortalProps,
  DialogRootProps,
  DialogViewportProps,
  DialogTitleProps,
  DialogTriggerProps,
} from '@base-ui/react';
