// Post-build script: generates dist/tokens.css and dist/tailwind-v4.css
// from the already-compiled dist/index.js. Run after tsup.

import { lightTokens, darkTokens } from '../dist/index.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, '../dist');

function varLines(tokens, indent = '  ') {
  return Object.entries(tokens)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join('\n');
}

function varBlock(tokens, selector) {
  return `${selector} {\n${varLines(tokens)}\n}`;
}

// ── tokens.css ────────────────────────────────────────────────────────────────
// A framework-agnostic static stylesheet. Three strategies in one file:
//   1. :root          → always-on light tokens (default)
//   2. .dark          → class-based dark mode (Next.js darkMode:'class', MUI)
//   3. @media         → OS-preference dark mode (no JS required)
const tokensCss = `/* @kodez/design-tokens — generated by build, do not edit
 * Import via:  <link rel="stylesheet" href="node_modules/@kodez/design-tokens/dist/tokens.css">
 * Or in CSS:   @import "@kodez/design-tokens/dist/tokens.css";
 */

${varBlock(lightTokens, ':root')}

${varBlock(darkTokens, '.dark')}

@media (prefers-color-scheme: dark) {
  :root:not(.light) {
${varLines(darkTokens, '    ')}
  }
}
`;

writeFileSync(resolve(distDir, 'tokens.css'), tokensCss);

// ── tailwind-v4.css ───────────────────────────────────────────────────────────
// For Tailwind v4 projects using CSS-first configuration.
// Bundles token injection + @theme inline mapping in one file.
//
// Usage in your CSS entry point:
//   @import "tailwindcss";
//   @import "@kodez/design-tokens/dist/tailwind-v4.css";
//
// Note on text/border naming: Tailwind v4 generates utility names from the
// --color-* variable name, so --color-text-primary → text-text-primary.
// Use text-[var(--text-primary)] arbitrary syntax for cleaner class names.

// Tokens to include in @theme (skip legacy aliases and gradient tokens)
const SKIP_PREFIXES = ['app-', 'ds-', 'page-', 'portal-'];
const GRADIENT_TOKENS = new Set(['page-gradient', 'page-gradient-muted', 'portal-hero-bg']);

function toThemeLine(key) {
  if (SKIP_PREFIXES.some(p => key.startsWith(p))) return null;
  if (GRADIENT_TOKENS.has(key)) return null;
  if (key === 'focus-ring') return `  --color-focus-ring: var(--${key});`;

  // Tokens already prefixed with 'color-' map directly (no double-prefix)
  if (key.startsWith('color-')) {
    return `  --${key}: var(--${key});`;
  }

  return `  --color-${key}: var(--${key});`;
}

const themeLines = Object.keys(lightTokens)
  .map(toThemeLine)
  .filter(Boolean)
  .join('\n');

const tailwindV4Css = `/* @kodez/design-tokens — Tailwind v4 integration
 * Generated by build, do not edit.
 *
 * Usage (after @import "tailwindcss"):
 *   @import "@kodez/design-tokens/dist/tailwind-v4.css";
 *
 * Generated utility examples:
 *   bg-surface-0  bg-surface-1  bg-surface-2
 *   bg-accent  bg-accent-hover  bg-accent-dim
 *   bg-danger  bg-danger-bg  bg-success  bg-success-bg
 *   bg-brand  bg-brand-hover
 *   text-text-primary  (see note above about naming)
 */

/* ── Token values ──────────────────────────────────────────────────────────── */

${varBlock(lightTokens, ':root')}

${varBlock(darkTokens, '.dark')}

@media (prefers-color-scheme: dark) {
  :root:not(.light) {
${varLines(darkTokens, '    ')}
  }
}

/* ── Tailwind v4 utility registration ──────────────────────────────────────── */

@theme inline {
${themeLines}

  --font-sans: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, monospace;
}
`;

writeFileSync(resolve(distDir, 'tailwind-v4.css'), tailwindV4Css);

console.log('  ✓ dist/tokens.css');
console.log('  ✓ dist/tailwind-v4.css');
