// Post-build script: generates dist/tokens.css and dist/tailwind-v4.css
import { lightTokens, darkTokens } from '../dist/index.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, '../dist');

function varLines(tokens, indent = '  ') {
  return Object.entries(tokens)
    .map(([k, v]) => `${indent}--kz-${k}: ${v};`)
    .join('\n');
}

function varBlock(tokens, selector) {
  return `${selector} {\n${varLines(tokens)}\n}`;
}

// ── tokens.css ────────────────────────────────────────────────────────────────
const tokensCss = `/* @kodez/design-tokens — generated by build, do not edit
 * Import via:  <link rel="stylesheet" href="node_modules/@kodez/design-tokens/dist/tokens.css">
 * Or in CSS:   @import "@kodez/design-tokens/dist/tokens.css";
 * All variables are prefixed with --kz- to avoid collisions.
 */

${varBlock(lightTokens, ':root')}

${varBlock(darkTokens, '.dark')}

@media (prefers-color-scheme: dark) {
  :root:not(.light) {
${varLines(darkTokens, '    ')}
  }
}
`;

writeFileSync(resolve(distDir, 'tokens.css'), tokensCss);

// ── tailwind-v4.css ───────────────────────────────────────────────────────────
// Tailwind class names stay unprefixed (bg-surface-0), but reference --kz- vars.
const allKeys = [...new Set([...Object.keys(lightTokens), ...Object.keys(darkTokens)])];

function toThemeLine(key) {
  return `  --color-${key}: var(--kz-${key});`;
}

const themeLines = allKeys.map(toThemeLine).join('\n');

const tailwindV4Css = `/* @kodez/design-tokens — Tailwind v4 integration
 * Generated by build, do not edit.
 *
 * Usage (after @import "tailwindcss"):
 *   @import "@kodez/design-tokens/dist/tailwind-v4.css";
 *
 * CSS vars use --kz- prefix. Tailwind classes stay unprefixed: bg-surface-0, text-primary, etc.
 */

${varBlock(lightTokens, ':root')}

${varBlock(darkTokens, '.dark')}

@media (prefers-color-scheme: dark) {
  :root:not(.light) {
${varLines(darkTokens, '    ')}
  }
}

@theme inline {
${themeLines}

  --font-sans: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, monospace;
}
`;

writeFileSync(resolve(distDir, 'tailwind-v4.css'), tailwindV4Css);

console.log('  ✓ dist/tokens.css');
console.log('  ✓ dist/tailwind-v4.css');
