// Post-build script: generates dist/tokens.css and dist/tailwind-v4.css
import { getCssVars } from '../dist/index.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, '../dist');

function varLines(mode, indent = '  ') {
  return Object.entries(getCssVars(mode))
    .map(([k, v]) => `${indent}${k}: ${v};`)
    .join('\n');
}

function varBlock(mode, selector) {
  return `${selector} {\n${varLines(mode)}\\n}`;
}

// ── tokens.css ────────────────────────────────────────────────────────────────
const tokensCss = `/* @kodez/design-tokens — generated by build, do not edit
 * Import via:  <link rel="stylesheet" href="node_modules/@kodez/design-tokens/dist/tokens.css">
 * Or in CSS:   @import "@kodez/design-tokens/dist/tokens.css";
 * All variables are prefixed with --kz- to avoid collisions.
 */

:root {
${varLines('light')}
}

.dark {
${varLines('dark')}
}

@media (prefers-color-scheme: dark) {
  :root:not(.light) {
${varLines('dark', '    ')}
  }
}
`;

writeFileSync(resolve(distDir, 'tokens.css'), tokensCss);

// ── tailwind-v4.css ───────────────────────────────────────────────────────────
// Tailwind class names stay unprefixed (bg-surface-0), but reference --kz- vars.
const allVarKeys = [...new Set([
  ...Object.keys(getCssVars('light')),
  ...Object.keys(getCssVars('dark')),
])];

// '--kz-surface-0' → '--color-surface-0: var(--kz-surface-0)'
const themeLines = allVarKeys
  .map(k => `  --color-${k.slice('--kz-'.length)}: var(${k});`)
  .join('\n');

const tailwindV4Css = `/* @kodez/design-tokens — Tailwind v4 integration
 * Generated by build, do not edit.
 *
 * Usage (after @import "tailwindcss"):
 *   @import "@kodez/design-tokens/dist/tailwind-v4.css";
 *
 * CSS vars use --kz- prefix. Tailwind classes stay unprefixed: bg-surface-0, text-primary, etc.
 */

:root {
${varLines('light')}
}

.dark {
${varLines('dark')}
}

@media (prefers-color-scheme: dark) {
  :root:not(.light) {
${varLines('dark', '    ')}
  }
}

@theme inline {
${themeLines}

  --font-sans: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, monospace;
}
`;

writeFileSync(resolve(distDir, 'tailwind-v4.css'), tailwindV4Css);

console.log('  ✓ dist/tokens.css');
console.log('  ✓ dist/tailwind-v4.css');
