// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Menubar as _Menubar } from '@base-ui/react';
import type { MenubarProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function Menubar({ className, ...props }: MenubarProps) {
  return <_Menubar className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/menubar';
