// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Avatar as _Avatar } from '@base-ui/react';
import type {
  AvatarRootProps,
  AvatarImageProps,
  AvatarFallbackProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: AvatarRootProps) {
  return <_Avatar.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Image({ className, ...props }: AvatarImageProps) {
  return <_Avatar.Image className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Fallback({ className, ...props }: AvatarFallbackProps) {
  return <_Avatar.Fallback className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Avatar = { Root, Image, Fallback };

export type {
  AvatarRootProps,
  AvatarImageProps,
  AvatarFallbackProps,
} from '@base-ui/react';
