// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Tooltip as _Tooltip } from '@base-ui/react';
import type {
  TooltipRootProps,
  TooltipTriggerProps,
  TooltipPortalProps,
  TooltipPositionerProps,
  TooltipPopupProps,
  TooltipArrowProps,
  TooltipProviderProps,
  TooltipViewportProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: TooltipRootProps) {
  return <_Tooltip.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: TooltipTriggerProps) {
  return <_Tooltip.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Portal({ className, ...props }: TooltipPortalProps) {
  return <_Tooltip.Portal className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Positioner({ className, ...props }: TooltipPositionerProps) {
  return <_Tooltip.Positioner className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Popup({ className, ...props }: TooltipPopupProps) {
  return <_Tooltip.Popup className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Arrow({ className, ...props }: TooltipArrowProps) {
  return <_Tooltip.Arrow className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Provider({ className, ...props }: TooltipProviderProps) {
  return <_Tooltip.Provider className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Viewport({ className, ...props }: TooltipViewportProps) {
  return <_Tooltip.Viewport className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Tooltip = { Root, Trigger, Portal, Positioner, Popup, Arrow, Provider, Viewport };

export type {
  TooltipRootProps,
  TooltipTriggerProps,
  TooltipPortalProps,
  TooltipPositionerProps,
  TooltipPopupProps,
  TooltipArrowProps,
  TooltipProviderProps,
  TooltipViewportProps,
} from '@base-ui/react';
