// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Toggle as _Toggle } from '@base-ui/react';
import type { ToggleProps } from '@base-ui/react';
import { cn } from '../../utils/cn.js';

export function Toggle({ className, ...props }: ToggleProps) {
  return <_Toggle className={cn(
    // TODO: add default token classes here
    // 'inline-flex items-center bg-accent text-inverse ...',
    className
  )} {...props} />;
}

export type * from '@base-ui/react/toggle';
