// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Accordion as _Accordion } from '@base-ui/react';
import type {
  AccordionRootProps,
  AccordionItemProps,
  AccordionHeaderProps,
  AccordionTriggerProps,
  AccordionPanelProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: AccordionRootProps) {
  return <_Accordion.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Item({ className, ...props }: AccordionItemProps) {
  return <_Accordion.Item className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Header({ className, ...props }: AccordionHeaderProps) {
  return <_Accordion.Header className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Trigger({ className, ...props }: AccordionTriggerProps) {
  return <_Accordion.Trigger className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Panel({ className, ...props }: AccordionPanelProps) {
  return <_Accordion.Panel className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Accordion = { Root, Item, Header, Trigger, Panel };

export type {
  AccordionRootProps,
  AccordionItemProps,
  AccordionHeaderProps,
  AccordionTriggerProps,
  AccordionPanelProps,
} from '@base-ui/react';
