// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Meter as _Meter } from '@base-ui/react';
import type {
  MeterRootProps,
  MeterTrackProps,
  MeterIndicatorProps,
  MeterValueProps,
  MeterLabelProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: MeterRootProps) {
  return <_Meter.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Track({ className, ...props }: MeterTrackProps) {
  return <_Meter.Track className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Indicator({ className, ...props }: MeterIndicatorProps) {
  return <_Meter.Indicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Value({ className, ...props }: MeterValueProps) {
  return <_Meter.Value className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Label({ className, ...props }: MeterLabelProps) {
  return <_Meter.Label className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Meter = { Root, Track, Indicator, Value, Label };

export type {
  MeterRootProps,
  MeterTrackProps,
  MeterIndicatorProps,
  MeterValueProps,
  MeterLabelProps,
} from '@base-ui/react';
