// Generated by scripts/generate-components.mjs — do not edit
// Re-generate: node scripts/generate-components.mjs

import { Slider as _Slider } from '@base-ui/react';
import type {
  SliderRootProps,
  SliderLabelProps,
  SliderValueProps,
  SliderControlProps,
  SliderTrackProps,
  SliderThumbProps,
  SliderIndicatorProps,
} from '@base-ui/react';
import { cn } from '../../utils/cn.js';

function Root({ className, ...props }: SliderRootProps) {
  return <_Slider.Root className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Label({ className, ...props }: SliderLabelProps) {
  return <_Slider.Label className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Value({ className, ...props }: SliderValueProps) {
  return <_Slider.Value className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Control({ className, ...props }: SliderControlProps) {
  return <_Slider.Control className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Track({ className, ...props }: SliderTrackProps) {
  return <_Slider.Track className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Thumb({ className, ...props }: SliderThumbProps) {
  return <_Slider.Thumb className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

function Indicator({ className, ...props }: SliderIndicatorProps) {
  return <_Slider.Indicator className={cn(
    // TODO: add default token classes here
    // 'bg-surface-1 text-primary ...',
    className
  )} {...props} />;
}

export const Slider = { Root, Label, Value, Control, Track, Thumb, Indicator };

export type {
  SliderRootProps,
  SliderLabelProps,
  SliderValueProps,
  SliderControlProps,
  SliderTrackProps,
  SliderThumbProps,
  SliderIndicatorProps,
} from '@base-ui/react';
